# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
  brockertracker:
    image: brokertracker:3
    volumes:
      - type: bind # mount the volume from the host machine
        source: ./brokerTrackerData # path on host machine --> relative to this compose.yml file
        target: /app/data # path inside container
    build:
      context: .